### PR TITLE
Fixes broken date autoextents

### LINKED ISSUE #71: @graph-paper/datagraphic does cannot use xType=time without domain
THis reproduces the issue:

https://svelte.dev/repl/d2292aec7619405fa45c483c25b08669?version=3.21.0

### PR DESCRIPTION
**Pull request by hamilton**
Closes #71

### CODE REVIEW

File: packages/datagraphic/DataGraphic.svelte [hunk 1]
```diff
@@ -319,16 +345,26 @@ const emptyValue = () => ({
...
 $: if (dataGraphicMounted) {
-  // initiateRollovers(svg)
   rollover.setSVG(svg);
   internalRolloverStore.subscribe((v) => {
     hoverValue = v;
   });
+
+  // here, we are technically waiting a tick before updating the domain tweens.
+  // This gives room for all the extents to be calculated before jumping into animating them.
+  // Without this, the graphkind of springs into place, which does not feel ideal.
```
Comment (hamilton) [inline packages/datagraphic/DataGraphic.svelte:363]:
```suggestion
  // Without this, the graph kind of springs into place, which does not feel ideal.
```
